config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'stats/show'

  resources :games

  root 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :user

	validates :buyin, :numericality => {:greater_than_or_equal_to => 0},
		:presence => true
	validates :buyout, :numericality => {:greater_than_or_equal_to => 0, 
		message: 'Winnings must be greater than or equal to zero.'},
		:presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /games
  # GET /games.json
  def index
    @games = current_user.games.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = current_user.games.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_user.games.new(game_params)
    @game.profit = @game.buyout - @game.buyin

    respond_to do |format|
      if @game.save
        format.html { redirect_to stats_show_path}
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    @game.profit = @game.buyout - @game.buyin

    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = current_user.games.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:played, :buyin, :buyout, :gametype)
    end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  helper_method :sort_column, :sort_direction, :where_column, :where_condition

  def show
    @games = current_user.games.where(where_column => where_condition).order(sort_column + ' ' + sort_direction)
  	@profit = 0
  	
  	@games.each do |game|
  		@profit += (game.buyout - game.buyin)
	end

  end

  private

  def sort_column
	Game.column_names.include?(params[:sort]) ? params[:sort] : "played"
  end

  def sort_direction
  	%w(asc desc).include?(params[:direction]) ? params[:direction] : "asc"
  end

  def where_column
    Game.column_names.include?(params[:where_key]) ? params[:where_key] : :buyout
  end

  def where_condition
    params[:where_value] ? params[:where_value] : [0..10000]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/stats_helper.rb
module StatsHelper

	def sortable(column, title = nil)
		title ||= column.titleize
		direction = (column == sort_column && sort_direction == 'asc') ? 'desc' : 'asc'
		link_to title, sort: column, direction: direction
	end

	def filterable(anchor, column = nil)
		if anchor != 'Clear Filter'
			link_to anchor, where_key: column, where_value: anchor
		else
			link_to 'Clear Filter', stats_show_path
		end
	end
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Game Type" %><br>
    <%= f.select :gametype, options_for_select(%w(Tournament Cash)) %><br>
  </div>
  <div class="field">
    <%= f.label :played %><br>
    <%= f.date_select :played %>
  </div>
  <div class="field">
    <%= f.label "Buy In" %><br>
    <%= f.number_field :buyin %>
  </div>
  <div class="field">
    <%= f.label "Winnings" %><br>
    <%= f.number_field :buyout %>
  </div>
  <div class="actions">
    <%= f.submit "New Game", class: 'btn' %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Welcome</h1>

<br>

<%= link_to 'New Game', new_game_path %>
<%= link_to 'Statistics', stats_show_path %>
<%= link_to 'Logout', :destroy_user_session, method: :delete %>

app/views/games/new.html.erb
<div class='centered'>
	<h2>Enter New Game</h2>
	<%= render 'form' %>
</div>

<div class='links'>
	<%= link_to 'Back', games_path %>
</div>

app/views/games/show.html.erb
<p>
  <strong>Played:</strong>
  <%= @game.played %>
</p>

<p>
  <strong>Buyin:</strong>
  <%= @game.buyin %>
</p>

<p>
  <strong>Winnings:</strong>
  <%= @game.buyout %>
</p>

<p>
  <strong>Profit:</strong>
  <%= @game.buyout - @game.buyin %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %> |
<%= link_to 'Statistics', stats_show_path %> |
<%= link_to 'New Game', new_game_path %> |
<%= link_to 'Logout', :destroy_user_session, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poker Stats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<section id='header'>

	<h1>Poker Stat Tracker</h1>

</section>
<section id='main'>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
</section>
</body>
</html>

app/views/stats/show.html.erb
<% unless @games.count == 0 %>
<div class='centered'>
<h2>Summary Statistics</h2>

<h3>You have played 
<%= pluralize(@games.count, "game") %>
so far.</h3>

<h3>So far you have
<% if @profit > 1 %>
  won $<%= @profit %>. Well done!
<% elsif @profit < 0 %>
  lost $<%= @profit.abs %>, you degenerate.
<% else %>
  broke even. Meh.
<% end %>

</h3>

<h3>You have
<% if @profit > 1 %>
  won an average of $<%= (@profit.to_f / @games.count).round(2) %> per game. Nice.
<% elsif @profit < 0 %>
  lost an average of $<%= (@profit.to_f / @games.count).round(2).abs %> per game. :-/
<% else %>
  an average winnings of zero. Talk about a waste of time...
<% end %>

<h3>Last game played
  <% days = [] %>
  <% @games.each do |game| %>
    <% day = (Time.now - game.played.to_datetime) / 86000 %>
    <% days << day.floor %>
  <% end %>
    <%= pluralize(days.min, "day") %> ago.</h3>

    <% if @games.count > 0 %>
<table>
  <thead>
    <tr>
      <th><%= sortable "played" %></th>
      <th><%= sortable "buyin" %></th>
      <th><%= sortable "buyout", 'Won' %></th>
      <th><%= sortable "profit" %></th>
      <th><%= sortable "gametype", 'Type' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= filterable game.played, 'played' %></td>
          <td><%= filterable game.buyin, 'buyin' %></td>
          <td><%= filterable game.buyout, 'buyout' %></td>
          <td><%= filterable game.profit, 'profit' %></td>
          <td><%= filterable game.gametype, 'gametype' %></td>
          <td> | </td>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        </tr>
      <% end %>
      <p class='centered'><%= filterable "Clear Filter" %></p>
    <% end %>
  </tbody>
 </table>

<% else %>
<h3>No Games Entered!</h3>
<% end %>
</div>
</br>
<div class='links'>
<%= link_to 'Back', games_path %> |
<%= link_to 'New Game', new_game_path %> |
<%= link_to 'Logout', :destroy_user_session, method: :delete %>
</div>